/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2019 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
#pragma once

/**
 * This file was generated by tltgen on Thu Jul  5 15:46:43 2018.
 * tltgen was created by Pieter Agten (pieter.agten@gmail.com).
 */
//#include "output_table.h"

#define NUMTEMPS 17
const short temptable_666[NUMTEMPS][2] PROGMEM = {
  { OV(  42.69 ), 241 }, // 250
  { OV(  50.31),  232 }, // 240
  { OV(  59.81 ), 222 }, // 230
  { OV(  72.19 ), 213 }, // 220
  { OV(  86.62 ), 203 }, // 210
  { OV( 101.69 ), 194 }, // 200
  { OV( 123.44 ), 184 }, // 190
  { OV( 151.69 ), 174 }, // 180
  { OV( 218.44 ), 155 }, // 160
  { OV( 317.88 ), 135 }, // 140
  { OV( 447.19 ), 115 }, // 120
  { OV( 590.63 ),  96 }, // 100
  { OV( 738.06 ),  77 }, // 80
  { OV( 859.56 ),  59 }, // 60
  { OV( 940.19 ),  41 }, // 40
  { OV( 959.25 ),  35 },
  { OV( 977.69 ),  28 }
};
